import { organisationSettingsService } from './organisationSettingsService';

export interface DocumentBrandingHeader {
  displayName: string;
  shortName?: string;
  logoUrl?: string;
  headerText?: string;
  email?: string;
  phone?: string;
  website?: string;
  address?: string;
  taxNumber?: string;
  registrationNumber?: string;
  primaryColor: string;
  secondaryColor: string;
}

export interface DocumentBrandingFooter {
  footerText: string;
  signature?: string;
  website?: string;
}

export const documentBrandingService = {
  /**
   * Resolves complete branding elements for document generation.
   */
  async getBranding(organisationId: string): Promise<{
    header: DocumentBrandingHeader;
    footer: DocumentBrandingFooter;
  }> {
    const settings = await organisationSettingsService.getSettings(organisationId);
    const { profile, branding } = settings;

    const addressParts = [
      profile.addressLine1,
      profile.addressLine2,
      profile.city,
      profile.provinceState,
      profile.postalCode,
      profile.country
    ].filter(Boolean);

    return {
      header: {
        displayName: branding.organisationDisplayName || profile.name,
        shortName: branding.shortName,
        logoUrl: branding.logoUrl,
        headerText: branding.documentHeaderText || profile.name,
        email: profile.email,
        phone: profile.phone,
        website: profile.website,
        address: addressParts.join(', '),
        taxNumber: profile.taxNumber,
        registrationNumber: profile.registrationNumber,
        primaryColor: branding.primaryBrandColour || '#4f46e5',
        secondaryColor: branding.secondaryBrandColour || '#0f172a'
      },
      footer: {
        footerText: branding.documentFooterText || 'Generated by ArtsFlow OS',
        signature: branding.emailSignature,
        website: profile.website
      }
    };
  },

  /**
   * Generates a reusable HTML header snippet for printable docs.
   */
  async formatHeaderHtml(organisationId: string): Promise<string> {
    const { header } = await this.getBranding(organisationId);
    return `
      <div style="display: flex; justify-content: space-between; align-items: flex-start; border-bottom: 2px solid ${header.primaryColor}; padding-bottom: 16px; margin-bottom: 24px;">
        <div>
          ${header.logoUrl ? `<img src="${header.logoUrl}" alt="Logo" style="max-height: 50px; margin-bottom: 8px;" />` : ''}
          <h1 style="margin: 0; font-size: 22px; color: ${header.secondaryColor}; font-weight: 700;">${header.displayName}</h1>
          ${header.headerText && header.headerText !== header.displayName ? `<p style="margin: 2px 0 0 0; color: #64748b; font-size: 13px;">${header.headerText}</p>` : ''}
        </div>
        <div style="text-align: right; font-size: 11px; color: #475569; line-height: 1.4;">
          ${header.address ? `<div>${header.address}</div>` : ''}
          ${header.email ? `<div>Email: ${header.email}</div>` : ''}
          ${header.phone ? `<div>Tel: ${header.phone}</div>` : ''}
          ${header.taxNumber ? `<div>Tax / VAT: ${header.taxNumber}</div>` : ''}
        </div>
      </div>
    `;
  },

  /**
   * Generates a reusable HTML footer snippet for printable docs.
   */
  async formatFooterHtml(organisationId: string): Promise<string> {
    const { footer } = await this.getBranding(organisationId);
    return `
      <div style="margin-top: 40px; border-top: 1px solid #e2e8f0; padding-top: 12px; font-size: 11px; color: #64748b; display: flex; justify-content: space-between;">
        <div>${footer.footerText}</div>
        ${footer.website ? `<div>${footer.website}</div>` : ''}
      </div>
    `;
  }
};
