import { organisationSettingsRepository } from '../repositories/organisationSettingsRepository';
import { organisationRepository } from '../repositories/organisationRepository';
import { auditService } from './auditService';
import type { 
  OrganisationSettings, 
  OrganisationAttendanceSettings, 
  OrganisationFinanceSettings, 
  OrganisationProfileSettings, 
  OrganisationStaffSettings, 
  OrganisationBrandingSettings,
  OrganisationConsentSettings,
  OrganisationTransportSettings,
  OrganisationDocumentSettings,
  AuditAction
} from '../types';

// In-memory cache for fast read performance
const settingsCache = new Map<string, { settings: OrganisationSettings; fetchedAt: number }>();
const CACHE_TTL_MS = 5 * 60 * 1000; // 5 minutes

export const DEFAULT_SETTINGS = (organisationId: string, orgName: string = 'My Organisation'): OrganisationSettings => ({
  id: organisationId,
  organisationId,
  createdAt: new Date().toISOString(),
  updatedAt: new Date().toISOString(),
  createdBy: 'system',
  updatedBy: 'system',
  status: 'active',
  profile: {
    name: orgName,
    organisationType: 'school_arts_programme',
    country: 'South Africa',
    timezone: 'Africa/Johannesburg',
    defaultCurrency: 'ZAR',
    locale: 'en-ZA',
    organisationStatus: 'active'
  },
  branding: {
    organisationDisplayName: orgName,
    shortName: orgName.slice(0, 8),
    primaryBrandColour: '#4f46e5',
    secondaryBrandColour: '#0f172a',
    documentHeaderText: orgName,
    documentFooterText: 'Generated by ArtsFlow OS'
  },
  programmes: {
    allowedProgrammeTypes: ['music', 'dance', 'drama', 'visual_arts', 'theatre', 'poetry', 'creative_arts', 'other'],
    defaultProgrammeStatus: 'active',
    defaultGroupCapacity: 15,
    defaultSessionDurationMinutes: 60,
    defaultSessionType: 'rehearsal',
    defaultAttendanceThreshold: 75
  },
  attendance: {
    lowAttendanceThresholdPercent: 75,
    consecutiveAbsenceThreshold: 3,
    lateCountsAsPresent: true,
    excusedCountsInDenominator: false,
    minimumSessionsForAttendanceAlert: 3,
    attendanceAutomationEnabled: true
  },
  finance: {
    defaultCurrency: 'ZAR',
    invoicePrefix: 'INV-',
    invoiceSequencePadding: 6,
    receiptPrefix: 'REC-',
    receiptSequencePadding: 6,
    defaultInvoiceDueDays: 30,
    allowUnallocatedPayments: true,
    financePeriodStartMonth: 1,
    taxEnabled: false,
    taxLabel: 'VAT',
    defaultTaxRate: 15
  },
  staff: {
    defaultTimesheetPeriod: 'monthly',
    timesheetVerificationRequired: true,
    timesheetApprovalRequired: true,
    preventSelfApproval: true,
    manualWorkEntryAllowed: true,
    maximumNormalWorkHoursPerDay: 12,
    substitutionApprovalRequired: true
  },
  consent: {
    defaultConsentDueDaysBeforeEvent: 14,
    requireParticipationConsent: true,
    requireTransportConsent: true,
    requireMedicalDeclaration: true,
    requireIndemnity: true,
    allowGuardianDigitalAcknowledgement: true,
    firstReminderDaysBeforeEvent: 7,
    urgentReminderDaysBeforeEvent: 2
  },
  transport: {
    requireTransportConsent: true,
    allowOverCapacityOverride: false,
    defaultMeetingLeadMinutes: 30,
    requireReturnCheck: true,
    requireDriverContact: true,
    requireVehicleCapacity: true
  },
  communication: {
    defaultGuardianChannel: 'email',
    defaultStaffChannel: 'email',
    whatsAppCountryCode: '+27',
    allowBulkGuardianCommunication: true,
    allowFinanceCommunication: true,
    allowAutomaticExternalSend: false
  },
  automation: {
    automationEnabled: true,
    defaultCooldownHours: 24,
    dryRunNewRulesByDefault: true,
    allowAutoCommunicationSend: false,
    notificationEscalationEnabled: true
  },
  documents: {
    defaultDocumentRetentionStatus: 'active',
    maximumUploadSizeMb: 10,
    allowedFileTypes: ['application/pdf', 'image/png', 'image/jpeg'],
    documentFooter: 'Confidential — ArtsFlow OS'
  },
  system: {
    defaultLandingPage: '/dashboard',
    dateFormat: 'YYYY-MM-DD',
    timeFormat: '24h',
    recordsPerPage: 25
  }
});

export const organisationSettingsService = {
  /**
   * Retrieves organisation settings with fallback defaults and transparent caching.
   */
  async getSettings(organisationId: string): Promise<OrganisationSettings> {
    const cached = settingsCache.get(organisationId);
    if (cached && Date.now() - cached.fetchedAt < CACHE_TTL_MS) {
      return cached.settings;
    }

    const existing = await organisationSettingsRepository.getByOrgId(organisationId);
    if (existing) {
      // Merge with default settings to ensure new fields are populated safely
      const org = await organisationRepository.getById(organisationId, organisationId);
      const defaults = DEFAULT_SETTINGS(organisationId, org?.name || 'My Organisation');
      const merged: OrganisationSettings = {
        ...defaults,
        ...existing,
        profile: { ...defaults.profile, ...existing.profile },
        branding: { ...defaults.branding, ...existing.branding },
        programmes: { ...defaults.programmes, ...existing.programmes },
        attendance: { ...defaults.attendance, ...existing.attendance },
        finance: { ...defaults.finance, ...existing.finance },
        staff: { ...defaults.staff, ...existing.staff },
        consent: { ...defaults.consent, ...existing.consent },
        transport: { ...defaults.transport, ...existing.transport },
        communication: { ...defaults.communication, ...existing.communication },
        automation: { ...defaults.automation, ...existing.automation },
        documents: { ...defaults.documents, ...existing.documents },
        system: { ...defaults.system, ...existing.system }
      };
      settingsCache.set(organisationId, { settings: merged, fetchedAt: Date.now() });
      return merged;
    }

    // Initialize defaults
    const org = await organisationRepository.getById(organisationId, organisationId);
    const defaults = DEFAULT_SETTINGS(organisationId, org?.name || 'My Organisation');
    await organisationSettingsRepository.setSettings(organisationId, 'system', defaults);
    settingsCache.set(organisationId, { settings: defaults, fetchedAt: Date.now() });
    return defaults;
  },

  /**
   * Updates a specific typed section of organisation settings with validation and audit logging.
   */
  async updateSection<K extends keyof OrganisationSettings>(
    organisationId: string,
    actorId: string,
    section: K,
    data: Partial<OrganisationSettings[K]>
  ): Promise<OrganisationSettings> {
    // 1. Validate section update
    this.validateSection(section, data);

    const current = await this.getSettings(organisationId);
    const before = current[section];
    const updatedSection = {
      ...(typeof before === 'object' && before !== null ? before : {}),
      ...data
    };

    // 2. Persist to Firestore
    await organisationSettingsRepository.updateSection(organisationId, actorId, section, updatedSection as Partial<OrganisationSettings[K]>);

    // 3. Invalidate cache
    settingsCache.delete(organisationId);

    // 4. Audit Log
    const auditActionMap: Record<string, AuditAction> = {
      profile: 'UPDATE_ORGANISATION_PROFILE',
      branding: 'UPDATE_BRANDING',
      programmes: 'UPDATE_PROGRAMME_SETTINGS',
      attendance: 'UPDATE_ATTENDANCE_SETTINGS',
      finance: 'UPDATE_FINANCE_SETTINGS',
      staff: 'UPDATE_STAFF_SETTINGS',
      consent: 'UPDATE_CONSENT_SETTINGS',
      transport: 'UPDATE_TRANSPORT_SETTINGS',
      communication: 'UPDATE_COMMUNICATION_SETTINGS',
      automation: 'UPDATE_AUTOMATION_SETTINGS',
      documents: 'UPDATE_DOCUMENT_SETTINGS',
      system: 'UPDATE_SYSTEM_SETTINGS'
    };

    const action = auditActionMap[section as string] || 'UPDATE';
    await auditService.log(
      organisationId,
      actorId,
      action,
      'organisationSettings',
      `${organisationId}_${String(section)}`,
      before,
      updatedSection
    );

    return this.getSettings(organisationId);
  },

  /**
   * Centralized configuration validators
   */
  validateSection(section: string, data: unknown): void {
    if (!data || typeof data !== 'object') {
      throw new Error('Settings data must be a valid object.');
    }

    if (section === 'attendance') {
      const att = data as Partial<OrganisationAttendanceSettings>;
      if (att.lowAttendanceThresholdPercent !== undefined) {
        if (att.lowAttendanceThresholdPercent < 0 || att.lowAttendanceThresholdPercent > 100) {
          throw new Error('Low attendance threshold must be between 0 and 100%.');
        }
      }
      if (att.consecutiveAbsenceThreshold !== undefined && att.consecutiveAbsenceThreshold < 1) {
        throw new Error('Consecutive absence threshold must be at least 1.');
      }
      if (att.minimumSessionsForAttendanceAlert !== undefined && att.minimumSessionsForAttendanceAlert < 1) {
        throw new Error('Minimum sessions for attendance alert must be at least 1.');
      }
    } else if (section === 'finance') {
      const fin = data as Partial<OrganisationFinanceSettings>;
      if (fin.defaultInvoiceDueDays !== undefined && fin.defaultInvoiceDueDays < 0) {
        throw new Error('Default invoice due days cannot be negative.');
      }
      if (fin.invoiceSequencePadding !== undefined && (fin.invoiceSequencePadding < 1 || fin.invoiceSequencePadding > 12)) {
        throw new Error('Invoice sequence padding must be between 1 and 12 digits.');
      }
      if (fin.receiptSequencePadding !== undefined && (fin.receiptSequencePadding < 1 || fin.receiptSequencePadding > 12)) {
        throw new Error('Receipt sequence padding must be between 1 and 12 digits.');
      }
      if (fin.defaultCurrency !== undefined && !/^[A-Z]{3}$/.test(fin.defaultCurrency.trim())) {
        throw new Error('Currency must be a valid 3-letter uppercase code (e.g. ZAR, USD, EUR).');
      }
      if (fin.defaultTaxRate !== undefined && (fin.defaultTaxRate < 0 || fin.defaultTaxRate > 100)) {
        throw new Error('Tax rate must be between 0 and 100%.');
      }
    } else if (section === 'profile') {
      const prof = data as Partial<OrganisationProfileSettings>;
      if (prof.timezone !== undefined) {
        try {
          Intl.DateTimeFormat(undefined, { timeZone: prof.timezone });
        } catch {
          throw new Error(`Invalid IANA timezone: "${prof.timezone}". Example: "Africa/Johannesburg".`);
        }
      }
      if (prof.email !== undefined && prof.email.trim() && !/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(prof.email.trim())) {
        throw new Error('Please enter a valid email address.');
      }
    } else if (section === 'staff') {
      const st = data as Partial<OrganisationStaffSettings>;
      if (st.maximumNormalWorkHoursPerDay !== undefined && (st.maximumNormalWorkHoursPerDay <= 0 || st.maximumNormalWorkHoursPerDay > 24)) {
        throw new Error('Maximum normal work hours per day must be between 1 and 24 hours.');
      }
    } else if (section === 'documents') {
      const doc = data as Partial<OrganisationDocumentSettings>;
      if (doc.maximumUploadSizeMb !== undefined && (doc.maximumUploadSizeMb <= 0 || doc.maximumUploadSizeMb > 100)) {
        throw new Error('Maximum upload size must be between 1MB and 100MB.');
      }
    } else if (section === 'transport') {
      const tr = data as Partial<OrganisationTransportSettings>;
      if (tr.defaultMeetingLeadMinutes !== undefined && tr.defaultMeetingLeadMinutes < 0) {
        throw new Error('Default meeting lead minutes cannot be negative.');
      }
    } else if (section === 'consent') {
      const cs = data as Partial<OrganisationConsentSettings>;
      if (cs.defaultConsentDueDaysBeforeEvent !== undefined && cs.defaultConsentDueDaysBeforeEvent < 0) {
        throw new Error('Consent due days before event cannot be negative.');
      }
      if (cs.firstReminderDaysBeforeEvent !== undefined && cs.firstReminderDaysBeforeEvent < 0) {
        throw new Error('Reminder days before event cannot be negative.');
      }
    } else if (section === 'branding') {
      const br = data as Partial<OrganisationBrandingSettings>;
      const hexRegex = /^#([0-9A-Fa-f]{3}|[0-9A-Fa-f]{6})$/;
      if (br.primaryBrandColour && !hexRegex.test(br.primaryBrandColour)) {
        throw new Error('Primary brand colour must be a valid hex code (e.g. #4f46e5).');
      }
      if (br.secondaryBrandColour && !hexRegex.test(br.secondaryBrandColour)) {
        throw new Error('Secondary brand colour must be a valid hex code (e.g. #0f172a).');
      }
    }
  },

  /**
   * Helper to invalidate memory cache when needed.
   */
  invalidateCache(organisationId?: string): void {
    if (organisationId) {
      settingsCache.delete(organisationId);
    } else {
      settingsCache.clear();
    }
  }
};
