import React, { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import {
  Sparkles,
  Building2,
  Music,
  Users,
  ShieldCheck,
  CheckCircle2,
  ArrowRight,
  ArrowLeft,
  AlertCircle,
  Plus
} from 'lucide-react';
import { OrganisationOnboardingLayout } from '../layouts/OrganisationOnboardingLayout';
import { useAuth } from '../../../contexts/AuthContext';
import { organisationRepository } from '../../../repositories/organisationRepository';
import { organisationSettingsRepository } from '../../../repositories/organisationSettingsRepository';
import { organisationOnboardingService } from '../../../services/onboarding/organisationOnboardingService';
import { organisationReadinessService, type ReadinessReport } from '../../../services/onboarding/organisationReadinessService';
import { programmeService } from '../../../services/programmeService';
import { programmeGroupService } from '../../../services/programmeGroupService';
import { platformOperationsService, type LearnerImportValidationResult } from '../../../services/platformOperationsService';
import type {
  Organisation,
  OnboardingStep
} from '../../../types';

export const OrganisationOnboardingPage: React.FC = () => {
  const navigate = useNavigate();
  const { organisationId, authUser } = useAuth();

  const [loading, setLoading] = useState(true);
  const [organisation, setOrganisation] = useState<Organisation | null>(null);
  const [effectiveSteps, setEffectiveSteps] = useState<OnboardingStep[]>([]);
  const [currentStep, setCurrentStep] = useState<OnboardingStep>('welcome');
  const [readiness, setReadiness] = useState<ReadinessReport | null>(null);
  const [actionLoading, setActionLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [completedSuccess, setCompletedSuccess] = useState(false);

  // Step Form States
  const [profileForm, setProfileForm] = useState({
    name: '',
    organisationType: 'school_arts_programme',
    phone: '',
    country: 'South Africa',
    timezone: 'Africa/Johannesburg',
    currency: 'ZAR'
  });

  const [brandingForm, setBrandingForm] = useState({
    shortName: '',
    primaryBrandColour: '#4f46e5',
    documentHeaderText: '',
    documentFooterText: 'Generated by ArtsFlow OS'
  });

  const [programmeTypes, setProgrammeTypes] = useState<string[]>(['music', 'dance']);

  const [calendarForm, setCalendarForm] = useState({
    termName: 'Term 1',
    startDate: `${new Date().getFullYear()}-01-15`,
    endDate: `${new Date().getFullYear()}-04-05`
  });

  const [attendanceForm, setAttendanceForm] = useState({
    lowAttendanceThresholdPercent: 75,
    consecutiveAbsenceThreshold: 3
  });

  const [financeForm, setFinanceForm] = useState({
    defaultCurrency: 'ZAR',
    invoicePrefix: 'INV-',
    defaultInvoiceDueDays: 30
  });

  const [staffForm, setStaffForm] = useState({
    name: '',
    email: '',
    role: 'teacher' as 'teacher' | 'programme_director' | 'finance'
  });
  const [invitedStaffList, setInvitedStaffList] = useState<Array<{ name: string; email: string; role: string }>>([]);

  const [programmeForm, setProgrammeForm] = useState({
    name: 'Music Department',
    code: 'MUSIC',
    type: 'music' as 'music' | 'dance' | 'theatre' | 'visual_arts' | 'other',
    groupName: 'Ensemble A',
    groupType: 'ensemble' as 'ensemble' | 'class' | 'orchestra' | 'choir' | 'band' | 'company' | 'troupe' | 'crew' | 'individual' | 'workshop' | 'other'
  });

  const [csvContent, setCsvContent] = useState('');
  const [csvValidation, setCsvValidation] = useState<LearnerImportValidationResult | null>(null);

  useEffect(() => {
    if (!organisationId) return;
    let isMounted = true;
    Promise.all([
      organisationRepository.getById(organisationId),
      organisationOnboardingService.getOnboarding(organisationId),
      organisationOnboardingService.getEffectiveSteps(organisationId),
      organisationReadinessService.evaluateReadiness(organisationId)
    ])
      .then(([org, ob, steps, read]) => {
        if (!isMounted) return;
        setOrganisation(org);
        setEffectiveSteps(steps);
        setReadiness(read);

        if (org) {
          setProfileForm({
            name: org.name || '',
            organisationType: org.organisationType || 'school_arts_programme',
            phone: org.phone || '',
            country: 'South Africa',
            timezone: 'Africa/Johannesburg',
            currency: 'ZAR'
          });
          setBrandingForm({
            shortName: org.name?.slice(0, 8) || '',
            primaryBrandColour: '#4f46e5',
            documentHeaderText: org.name || '',
            documentFooterText: 'Generated by ArtsFlow OS'
          });
        }

        if (ob) {
          setCurrentStep(ob.currentStep);
          if (ob.onboardingStatus === 'completed') {
            setCompletedSuccess(true);
          }
        }
        setLoading(false);
      })
      .catch((err) => {
        if (!isMounted) return;
        setError((err as Error).message || 'Failed to load onboarding status');
        setLoading(false);
      });

    return () => {
      isMounted = false;
    };
  }, [organisationId]);

  const currentStepIndex = effectiveSteps.indexOf(currentStep);
  const totalSteps = effectiveSteps.length;

  const handleNext = async (stepData?: Record<string, unknown>) => {
    if (!organisationId || !authUser) return;
    try {
      setActionLoading(true);
      setError(null);

      const updated = await organisationOnboardingService.completeStep(
        authUser.uid,
        organisationId,
        currentStep,
        stepData
      );
      setCurrentStep(updated.currentStep);

      // Refresh readiness
      const newReadiness = await organisationReadinessService.evaluateReadiness(organisationId);
      setReadiness(newReadiness);
    } catch (err) {
      setError((err as Error).message || 'Failed to advance step');
    } finally {
      setActionLoading(false);
    }
  };

  const handleSkip = async () => {
    if (!organisationId || !authUser) return;
    try {
      setActionLoading(true);
      setError(null);

      const updated = await organisationOnboardingService.skipStep(
        authUser.uid,
        organisationId,
        currentStep
      );
      setCurrentStep(updated.currentStep);
    } catch (err) {
      setError((err as Error).message || 'Failed to skip step');
    } finally {
      setActionLoading(false);
    }
  };

  const handleSaveProfile = async () => {
    if (!organisationId || !authUser) return;
    try {
      setActionLoading(true);
      await organisationRepository.update(organisationId, authUser.uid, {
        name: profileForm.name.trim(),
        organisationType: profileForm.organisationType.trim(),
        phone: profileForm.phone.trim() || undefined
      });

      await organisationSettingsRepository.updateSection(organisationId, authUser.uid, 'profile', {
        name: profileForm.name.trim(),
        organisationType: profileForm.organisationType.trim(),
        country: profileForm.country,
        timezone: profileForm.timezone,
        defaultCurrency: profileForm.currency
      });

      await handleNext(profileForm);
    } catch (err) {
      setError((err as Error).message || 'Failed to save profile');
      setActionLoading(false);
    }
  };

  const handleSaveBranding = async () => {
    if (!organisationId || !authUser) return;
    try {
      setActionLoading(true);
      await organisationSettingsRepository.updateSection(organisationId, authUser.uid, 'branding', {
        shortName: brandingForm.shortName.trim(),
        primaryBrandColour: brandingForm.primaryBrandColour,
        documentHeaderText: brandingForm.documentHeaderText.trim(),
        documentFooterText: brandingForm.documentFooterText.trim()
      });
      await handleNext(brandingForm);
    } catch (err) {
      setError((err as Error).message || 'Failed to save branding');
      setActionLoading(false);
    }
  };

  const handleSaveAttendance = async () => {
    if (!organisationId || !authUser) return;
    try {
      setActionLoading(true);
      await organisationSettingsRepository.updateSection(organisationId, authUser.uid, 'attendance', {
        lowAttendanceThresholdPercent: attendanceForm.lowAttendanceThresholdPercent,
        consecutiveAbsenceThreshold: attendanceForm.consecutiveAbsenceThreshold
      });
      await handleNext(attendanceForm);
    } catch (err) {
      setError((err as Error).message || 'Failed to save attendance defaults');
      setActionLoading(false);
    }
  };

  const handleSaveFinance = async () => {
    if (!organisationId || !authUser) return;
    try {
      setActionLoading(true);
      await organisationSettingsRepository.updateSection(organisationId, authUser.uid, 'finance', {
        defaultCurrency: financeForm.defaultCurrency,
        invoicePrefix: financeForm.invoicePrefix.trim(),
        defaultInvoiceDueDays: financeForm.defaultInvoiceDueDays
      });
      await handleNext(financeForm);
    } catch (err) {
      setError((err as Error).message || 'Failed to save finance settings');
      setActionLoading(false);
    }
  };

  const handleCreateProgrammeAndGroup = async () => {
    if (!organisationId || !authUser) return;
    try {
      setActionLoading(true);
      const prog = await programmeService.createProgramme(organisationId, authUser.uid, {
        name: programmeForm.name.trim(),
        description: `Code: ${programmeForm.code.trim().toUpperCase()}`,
        programmeType: programmeForm.type
      });

      await programmeGroupService.createGroup(organisationId, authUser.uid, {
        programmeId: prog.id,
        name: programmeForm.groupName.trim(),
        groupType: programmeForm.groupType
      });

      await handleNext(programmeForm);
    } catch (err) {
      setError((err as Error).message || 'Failed to create programme and group');
      setActionLoading(false);
    }
  };

  const handleValidateCsv = () => {
    const res = platformOperationsService.validateLearnerImportCsv(csvContent);
    setCsvValidation(res);
  };

  const handleGoLive = async () => {
    if (!organisationId || !authUser) return;
    try {
      setActionLoading(true);
      setError(null);
      await organisationReadinessService.completeOrganisationOnboarding(authUser.uid, organisationId);
      setCompletedSuccess(true);
    } catch (err) {
      setError((err as Error).message || 'Failed to complete go-live');
    } finally {
      setActionLoading(false);
    }
  };

  if (loading) {
    return (
      <div className="min-h-screen bg-slate-900 flex items-center justify-center text-slate-300">
        <div className="flex flex-col items-center gap-3">
          <div className="w-8 h-8 border-2 border-indigo-500 border-t-transparent rounded-full animate-spin" />
          <p className="text-sm">Loading onboarding wizard...</p>
        </div>
      </div>
    );
  }

  if (completedSuccess) {
    return (
      <div className="min-h-screen bg-slate-900 flex items-center justify-center p-4">
        <div className="max-w-md w-full bg-slate-800/90 border border-slate-700 rounded-2xl p-8 text-center space-y-6">
          <div className="w-16 h-16 bg-emerald-500/20 text-emerald-400 border border-emerald-500/30 rounded-full flex items-center justify-center mx-auto">
            <CheckCircle2 className="w-10 h-10" />
          </div>
          <div className="space-y-2">
            <h2 className="text-2xl font-bold text-white">Your School is Live!</h2>
            <p className="text-sm text-slate-300">
              {organisation?.name} is officially operational on ArtsFlow OS. Your initial programmes, settings, and staff are configured.
            </p>
          </div>
          <button
            onClick={() => navigate('/dashboard')}
            className="w-full py-3 px-4 bg-indigo-600 hover:bg-indigo-500 text-white rounded-xl font-medium transition flex items-center justify-center gap-2"
          >
            Go to Main Dashboard
            <ArrowRight className="w-4 h-4" />
          </button>
        </div>
      </div>
    );
  }

  const stepTitles: Record<OnboardingStep, string> = {
    welcome: 'Welcome to ArtsFlow OS',
    organisation_profile: 'Organisation Profile',
    branding: 'School Branding & Identity',
    programme_types: 'Arts Programme Disciplines',
    calendar: 'Academic Year & Term Schedule',
    attendance: 'Attendance Policy Defaults',
    finance: 'Finance & Invoicing Setup',
    staff: 'Invite Teaching Staff',
    programmes_groups: 'First Programme & Class',
    learner_import: 'Import Learners (CSV)',
    guardian_setup: 'Guardian Readiness',
    review: 'Review Setup & Readiness',
    go_live: 'Ready to Go Live'
  };

  return (
    <OrganisationOnboardingLayout
      organisationName={organisation?.name || 'Organisation'}
      currentStepIndex={currentStepIndex}
      totalSteps={totalSteps}
      stepTitle={stepTitles[currentStep] || 'Setup'}
    >
      {error && (
        <div className="mb-6 p-4 rounded-xl bg-rose-500/10 border border-rose-500/30 text-rose-300 text-sm flex items-start gap-3">
          <AlertCircle className="w-5 h-5 flex-shrink-0 mt-0.5" />
          <div>{error}</div>
        </div>
      )}

      {/* STEP 1: WELCOME */}
      {currentStep === 'welcome' && (
        <div className="bg-slate-800/60 border border-slate-700/80 rounded-2xl p-8 space-y-6">
          <div className="space-y-3">
            <h2 className="text-xl font-semibold text-white">Let's set up your arts organisation</h2>
            <p className="text-slate-300 text-sm leading-relaxed">
              This guided setup wizard will help you configure your organisation profile, academic calendar, teaching disciplines, first classes, and invite key staff.
            </p>
          </div>

          <div className="grid grid-cols-1 sm:grid-cols-2 gap-4 py-2">
            <div className="p-4 rounded-xl bg-slate-900/60 border border-slate-700/50 space-y-1">
              <div className="flex items-center gap-2 text-indigo-400 font-medium text-sm">
                <Building2 className="w-4 h-4" />
                Profile & Branding
              </div>
              <p className="text-xs text-slate-400">School identity, contact details, and document templates.</p>
            </div>
            <div className="p-4 rounded-xl bg-slate-900/60 border border-slate-700/50 space-y-1">
              <div className="flex items-center gap-2 text-indigo-400 font-medium text-sm">
                <Music className="w-4 h-4" />
                Programmes & Classes
              </div>
              <p className="text-xs text-slate-400">Set up your initial arts disciplines, bands, choirs, or studios.</p>
            </div>
            <div className="p-4 rounded-xl bg-slate-900/60 border border-slate-700/50 space-y-1">
              <div className="flex items-center gap-2 text-indigo-400 font-medium text-sm">
                <Users className="w-4 h-4" />
                Staff Invitations
              </div>
              <p className="text-xs text-slate-400">Bring teachers and administrators into your workspace.</p>
            </div>
            <div className="p-4 rounded-xl bg-slate-900/60 border border-slate-700/50 space-y-1">
              <div className="flex items-center gap-2 text-indigo-400 font-medium text-sm">
                <ShieldCheck className="w-4 h-4" />
                Safety & Readiness
              </div>
              <p className="text-xs text-slate-400">Automated readiness checks before going live to parents.</p>
            </div>
          </div>

          <div className="pt-4 flex items-center justify-end">
            <button
              onClick={() => handleNext()}
              disabled={actionLoading}
              className="py-2.5 px-6 bg-indigo-600 hover:bg-indigo-500 text-white rounded-xl font-medium transition flex items-center gap-2"
            >
              Get Started
              <ArrowRight className="w-4 h-4" />
            </button>
          </div>
        </div>
      )}

      {/* STEP 2: PROFILE */}
      {currentStep === 'organisation_profile' && (
        <div className="bg-slate-800/60 border border-slate-700/80 rounded-2xl p-8 space-y-6">
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
            <div className="space-y-1.5 sm:col-span-2">
              <label className="text-xs font-medium text-slate-300">Organisation Name *</label>
              <input
                type="text"
                value={profileForm.name}
                onChange={(e) => setProfileForm({ ...profileForm, name: e.target.value })}
                className="w-full bg-slate-900 border border-slate-700 rounded-xl px-3 py-2 text-white text-sm focus:outline-none focus:border-indigo-500"
              />
            </div>

            <div className="space-y-1.5">
              <label className="text-xs font-medium text-slate-300">Organisation Type</label>
              <select
                value={profileForm.organisationType}
                onChange={(e) => setProfileForm({ ...profileForm, organisationType: e.target.value })}
                className="w-full bg-slate-900 border border-slate-700 rounded-xl px-3 py-2 text-white text-sm focus:outline-none focus:border-indigo-500"
              >
                <option value="school_arts_programme">School Arts Department</option>
                <option value="music_academy">Music Academy</option>
                <option value="dance_academy">Dance Studio / Academy</option>
                <option value="community_arts_centre">Community Arts Project</option>
                <option value="arts_ngo">Arts NGO / Foundation</option>
              </select>
            </div>

            <div className="space-y-1.5">
              <label className="text-xs font-medium text-slate-300">Contact Phone</label>
              <input
                type="text"
                value={profileForm.phone}
                onChange={(e) => setProfileForm({ ...profileForm, phone: e.target.value })}
                placeholder="+27 11 000 0000"
                className="w-full bg-slate-900 border border-slate-700 rounded-xl px-3 py-2 text-white text-sm focus:outline-none focus:border-indigo-500"
              />
            </div>

            <div className="space-y-1.5">
              <label className="text-xs font-medium text-slate-300">Country</label>
              <input
                type="text"
                value={profileForm.country}
                onChange={(e) => setProfileForm({ ...profileForm, country: e.target.value })}
                className="w-full bg-slate-900 border border-slate-700 rounded-xl px-3 py-2 text-white text-sm focus:outline-none focus:border-indigo-500"
              />
            </div>

            <div className="space-y-1.5">
              <label className="text-xs font-medium text-slate-300">Currency</label>
              <select
                value={profileForm.currency}
                onChange={(e) => setProfileForm({ ...profileForm, currency: e.target.value })}
                className="w-full bg-slate-900 border border-slate-700 rounded-xl px-3 py-2 text-white text-sm focus:outline-none focus:border-indigo-500"
              >
                <option value="ZAR">South African Rand (ZAR)</option>
                <option value="USD">US Dollar (USD)</option>
                <option value="GBP">British Pound (GBP)</option>
                <option value="EUR">Euro (EUR)</option>
              </select>
            </div>
          </div>

          <div className="pt-4 flex items-center justify-end gap-3">
            <button
              onClick={handleSaveProfile}
              disabled={actionLoading || !profileForm.name.trim()}
              className="py-2.5 px-6 bg-indigo-600 hover:bg-indigo-500 text-white rounded-xl font-medium transition flex items-center gap-2"
            >
              Save & Continue
              <ArrowRight className="w-4 h-4" />
            </button>
          </div>
        </div>
      )}

      {/* STEP 3: BRANDING */}
      {currentStep === 'branding' && (
        <div className="bg-slate-800/60 border border-slate-700/80 rounded-2xl p-8 space-y-6">
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
            <div className="space-y-1.5">
              <label className="text-xs font-medium text-slate-300">Short Name / Code</label>
              <input
                type="text"
                value={brandingForm.shortName}
                onChange={(e) => setBrandingForm({ ...brandingForm, shortName: e.target.value })}
                className="w-full bg-slate-900 border border-slate-700 rounded-xl px-3 py-2 text-white text-sm focus:outline-none focus:border-indigo-500"
              />
            </div>

            <div className="space-y-1.5">
              <label className="text-xs font-medium text-slate-300">Primary Brand Colour</label>
              <div className="flex items-center gap-2">
                <input
                  type="color"
                  value={brandingForm.primaryBrandColour}
                  onChange={(e) => setBrandingForm({ ...brandingForm, primaryBrandColour: e.target.value })}
                  className="w-10 h-10 rounded-lg bg-transparent cursor-pointer border border-slate-700"
                />
                <input
                  type="text"
                  value={brandingForm.primaryBrandColour}
                  onChange={(e) => setBrandingForm({ ...brandingForm, primaryBrandColour: e.target.value })}
                  className="flex-1 bg-slate-900 border border-slate-700 rounded-xl px-3 py-2 text-white text-sm font-mono focus:outline-none focus:border-indigo-500"
                />
              </div>
            </div>

            <div className="space-y-1.5 sm:col-span-2">
              <label className="text-xs font-medium text-slate-300">Document Header Text</label>
              <input
                type="text"
                value={brandingForm.documentHeaderText}
                onChange={(e) => setBrandingForm({ ...brandingForm, documentHeaderText: e.target.value })}
                placeholder="e.g. Soweto Arts Academy — Department of Music"
                className="w-full bg-slate-900 border border-slate-700 rounded-xl px-3 py-2 text-white text-sm focus:outline-none focus:border-indigo-500"
              />
            </div>
          </div>

          <div className="pt-4 flex items-center justify-between">
            <button
              onClick={handleSkip}
              className="text-xs text-slate-400 hover:text-white py-2 px-3 rounded-lg hover:bg-slate-700/50 transition"
            >
              Skip for now
            </button>
            <button
              onClick={handleSaveBranding}
              disabled={actionLoading}
              className="py-2.5 px-6 bg-indigo-600 hover:bg-indigo-500 text-white rounded-xl font-medium transition flex items-center gap-2"
            >
              Save & Continue
              <ArrowRight className="w-4 h-4" />
            </button>
          </div>
        </div>
      )}

      {/* STEP 4: PROGRAMME TYPES */}
      {currentStep === 'programme_types' && (
        <div className="bg-slate-800/60 border border-slate-700/80 rounded-2xl p-8 space-y-6">
          <p className="text-sm text-slate-300">
            Select the primary arts disciplines your organisation provides:
          </p>

          <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
            {[
              { id: 'music', label: 'Music (Instruments, Voice, Choirs)' },
              { id: 'dance', label: 'Dance (Ballet, Contemporary, Street)' },
              { id: 'theatre', label: 'Drama & Theatre Arts' },
              { id: 'visual_arts', label: 'Visual Arts & Media' }
            ].map((disc) => (
              <label
                key={disc.id}
                className={`p-4 rounded-xl border cursor-pointer flex items-center gap-3 transition ${
                  programmeTypes.includes(disc.id)
                    ? 'bg-indigo-600/15 border-indigo-500/50 text-white'
                    : 'bg-slate-900/60 border-slate-700/50 text-slate-300 hover:border-slate-600'
                }`}
              >
                <input
                  type="checkbox"
                  checked={programmeTypes.includes(disc.id)}
                  onChange={(e) => {
                    if (e.target.checked) {
                      setProgrammeTypes([...programmeTypes, disc.id]);
                    } else {
                      setProgrammeTypes(programmeTypes.filter((t) => t !== disc.id));
                    }
                  }}
                  className="w-4 h-4 rounded text-indigo-600 focus:ring-0 focus:outline-none"
                />
                <span className="text-sm font-medium">{disc.label}</span>
              </label>
            ))}
          </div>

          <div className="pt-4 flex items-center justify-end">
            <button
              onClick={() => handleNext({ programmeTypes })}
              disabled={actionLoading || programmeTypes.length === 0}
              className="py-2.5 px-6 bg-indigo-600 hover:bg-indigo-500 text-white rounded-xl font-medium transition flex items-center gap-2"
            >
              Continue
              <ArrowRight className="w-4 h-4" />
            </button>
          </div>
        </div>
      )}

      {/* STEP 5: CALENDAR */}
      {currentStep === 'calendar' && (
        <div className="bg-slate-800/60 border border-slate-700/80 rounded-2xl p-8 space-y-6">
          <div className="grid grid-cols-1 sm:grid-cols-3 gap-4">
            <div className="space-y-1.5 sm:col-span-3">
              <label className="text-xs font-medium text-slate-300">Initial Period Name</label>
              <input
                type="text"
                value={calendarForm.termName}
                onChange={(e) => setCalendarForm({ ...calendarForm, termName: e.target.value })}
                className="w-full bg-slate-900 border border-slate-700 rounded-xl px-3 py-2 text-white text-sm focus:outline-none focus:border-indigo-500"
              />
            </div>
            <div className="space-y-1.5">
              <label className="text-xs font-medium text-slate-300">Start Date</label>
              <input
                type="date"
                value={calendarForm.startDate}
                onChange={(e) => setCalendarForm({ ...calendarForm, startDate: e.target.value })}
                className="w-full bg-slate-900 border border-slate-700 rounded-xl px-3 py-2 text-white text-sm focus:outline-none focus:border-indigo-500"
              />
            </div>
            <div className="space-y-1.5">
              <label className="text-xs font-medium text-slate-300">End Date</label>
              <input
                type="date"
                value={calendarForm.endDate}
                onChange={(e) => setCalendarForm({ ...calendarForm, endDate: e.target.value })}
                className="w-full bg-slate-900 border border-slate-700 rounded-xl px-3 py-2 text-white text-sm focus:outline-none focus:border-indigo-500"
              />
            </div>
          </div>

          <div className="pt-4 flex items-center justify-between">
            <button
              onClick={handleSkip}
              className="text-xs text-slate-400 hover:text-white py-2 px-3 rounded-lg hover:bg-slate-700/50 transition"
            >
              Skip for now
            </button>
            <button
              onClick={() => handleNext(calendarForm)}
              disabled={actionLoading}
              className="py-2.5 px-6 bg-indigo-600 hover:bg-indigo-500 text-white rounded-xl font-medium transition flex items-center gap-2"
            >
              Save Period
              <ArrowRight className="w-4 h-4" />
            </button>
          </div>
        </div>
      )}

      {/* STEP 6: ATTENDANCE */}
      {currentStep === 'attendance' && (
        <div className="bg-slate-800/60 border border-slate-700/80 rounded-2xl p-8 space-y-6">
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
            <div className="space-y-1.5">
              <label className="text-xs font-medium text-slate-300">Low Attendance Warning Threshold (%)</label>
              <input
                type="number"
                min="50"
                max="100"
                value={attendanceForm.lowAttendanceThresholdPercent}
                onChange={(e) => setAttendanceForm({ ...attendanceForm, lowAttendanceThresholdPercent: Number(e.target.value) })}
                className="w-full bg-slate-900 border border-slate-700 rounded-xl px-3 py-2 text-white text-sm focus:outline-none focus:border-indigo-500"
              />
            </div>

            <div className="space-y-1.5">
              <label className="text-xs font-medium text-slate-300">Consecutive Absence Alert (Sessions)</label>
              <input
                type="number"
                min="1"
                max="10"
                value={attendanceForm.consecutiveAbsenceThreshold}
                onChange={(e) => setAttendanceForm({ ...attendanceForm, consecutiveAbsenceThreshold: Number(e.target.value) })}
                className="w-full bg-slate-900 border border-slate-700 rounded-xl px-3 py-2 text-white text-sm focus:outline-none focus:border-indigo-500"
              />
            </div>
          </div>

          <div className="pt-4 flex items-center justify-end">
            <button
              onClick={handleSaveAttendance}
              disabled={actionLoading}
              className="py-2.5 px-6 bg-indigo-600 hover:bg-indigo-500 text-white rounded-xl font-medium transition flex items-center gap-2"
            >
              Save & Continue
              <ArrowRight className="w-4 h-4" />
            </button>
          </div>
        </div>
      )}

      {/* STEP 7: FINANCE */}
      {currentStep === 'finance' && (
        <div className="bg-slate-800/60 border border-slate-700/80 rounded-2xl p-8 space-y-6">
          <div className="grid grid-cols-1 sm:grid-cols-3 gap-4">
            <div className="space-y-1.5">
              <label className="text-xs font-medium text-slate-300">Billing Currency</label>
              <select
                value={financeForm.defaultCurrency}
                onChange={(e) => setFinanceForm({ ...financeForm, defaultCurrency: e.target.value })}
                className="w-full bg-slate-900 border border-slate-700 rounded-xl px-3 py-2 text-white text-sm focus:outline-none focus:border-indigo-500"
              >
                <option value="ZAR">ZAR (Rands)</option>
                <option value="USD">USD ($)</option>
                <option value="GBP">GBP (£)</option>
              </select>
            </div>

            <div className="space-y-1.5">
              <label className="text-xs font-medium text-slate-300">Invoice Number Prefix</label>
              <input
                type="text"
                value={financeForm.invoicePrefix}
                onChange={(e) => setFinanceForm({ ...financeForm, invoicePrefix: e.target.value })}
                className="w-full bg-slate-900 border border-slate-700 rounded-xl px-3 py-2 text-white text-sm focus:outline-none focus:border-indigo-500"
              />
            </div>

            <div className="space-y-1.5">
              <label className="text-xs font-medium text-slate-300">Payment Due (Days)</label>
              <input
                type="number"
                value={financeForm.defaultInvoiceDueDays}
                onChange={(e) => setFinanceForm({ ...financeForm, defaultInvoiceDueDays: Number(e.target.value) })}
                className="w-full bg-slate-900 border border-slate-700 rounded-xl px-3 py-2 text-white text-sm focus:outline-none focus:border-indigo-500"
              />
            </div>
          </div>

          <div className="pt-4 flex items-center justify-between">
            <button
              onClick={handleSkip}
              className="text-xs text-slate-400 hover:text-white py-2 px-3 rounded-lg hover:bg-slate-700/50 transition"
            >
              Skip for now
            </button>
            <button
              onClick={handleSaveFinance}
              disabled={actionLoading}
              className="py-2.5 px-6 bg-indigo-600 hover:bg-indigo-500 text-white rounded-xl font-medium transition flex items-center gap-2"
            >
              Save Finance Defaults
              <ArrowRight className="w-4 h-4" />
            </button>
          </div>
        </div>
      )}

      {/* STEP 8: STAFF */}
      {currentStep === 'staff' && (
        <div className="bg-slate-800/60 border border-slate-700/80 rounded-2xl p-8 space-y-6">
          <div className="grid grid-cols-1 sm:grid-cols-3 gap-3">
            <div className="space-y-1.5">
              <label className="text-xs font-medium text-slate-300">Name</label>
              <input
                type="text"
                value={staffForm.name}
                onChange={(e) => setStaffForm({ ...staffForm, name: e.target.value })}
                placeholder="Teacher Name"
                className="w-full bg-slate-900 border border-slate-700 rounded-xl px-3 py-2 text-white text-sm focus:outline-none focus:border-indigo-500"
              />
            </div>
            <div className="space-y-1.5">
              <label className="text-xs font-medium text-slate-300">Email Address</label>
              <input
                type="email"
                value={staffForm.email}
                onChange={(e) => setStaffForm({ ...staffForm, email: e.target.value })}
                placeholder="teacher@school.com"
                className="w-full bg-slate-900 border border-slate-700 rounded-xl px-3 py-2 text-white text-sm focus:outline-none focus:border-indigo-500"
              />
            </div>
            <div className="space-y-1.5">
              <label className="text-xs font-medium text-slate-300">Role</label>
              <div className="flex items-center gap-2">
                <select
                  value={staffForm.role}
                  onChange={(e) => setStaffForm({ ...staffForm, role: e.target.value as 'teacher' | 'programme_director' | 'finance' })}
                  className="flex-1 bg-slate-900 border border-slate-700 rounded-xl px-3 py-2 text-white text-sm focus:outline-none focus:border-indigo-500"
                >
                  <option value="teacher">Teacher / Instructor</option>
                  <option value="programme_director">Programme Director</option>
                  <option value="finance">Finance Officer</option>
                </select>
                <button
                  type="button"
                  onClick={() => {
                    if (staffForm.email.trim()) {
                      setInvitedStaffList([...invitedStaffList, staffForm]);
                      setStaffForm({ name: '', email: '', role: 'teacher' });
                    }
                  }}
                  className="p-2 bg-indigo-600 hover:bg-indigo-500 text-white rounded-xl transition"
                >
                  <Plus className="w-5 h-5" />
                </button>
              </div>
            </div>
          </div>

          {invitedStaffList.length > 0 && (
            <div className="border border-slate-700 rounded-xl overflow-hidden">
              <table className="w-full text-left text-xs">
                <thead className="bg-slate-900 text-slate-400">
                  <tr>
                    <th className="p-3">Name</th>
                    <th className="p-3">Email</th>
                    <th className="p-3">Role</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-slate-800 text-slate-200">
                  {invitedStaffList.map((st, i) => (
                    <tr key={i}>
                      <td className="p-3">{st.name || '—'}</td>
                      <td className="p-3 font-mono">{st.email}</td>
                      <td className="p-3 capitalize">{st.role.replace('_', ' ')}</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          )}

          <div className="pt-4 flex items-center justify-between">
            <button
              onClick={handleSkip}
              className="text-xs text-slate-400 hover:text-white py-2 px-3 rounded-lg hover:bg-slate-700/50 transition"
            >
              Skip for now
            </button>
            <button
              onClick={() => handleNext({ invitedStaff: invitedStaffList })}
              disabled={actionLoading}
              className="py-2.5 px-6 bg-indigo-600 hover:bg-indigo-500 text-white rounded-xl font-medium transition flex items-center gap-2"
            >
              Save & Continue
              <ArrowRight className="w-4 h-4" />
            </button>
          </div>
        </div>
      )}

      {/* STEP 9: PROGRAMMES & GROUPS */}
      {currentStep === 'programmes_groups' && (
        <div className="bg-slate-800/60 border border-slate-700/80 rounded-2xl p-8 space-y-6">
          <p className="text-sm text-slate-300">
            Create your first arts teaching programme and initial ensemble or class:
          </p>

          <div className="grid grid-cols-1 sm:grid-cols-3 gap-4">
            <div className="space-y-1.5 sm:col-span-2">
              <label className="text-xs font-medium text-slate-300">Programme Name</label>
              <input
                type="text"
                value={programmeForm.name}
                onChange={(e) => setProgrammeForm({ ...programmeForm, name: e.target.value })}
                className="w-full bg-slate-900 border border-slate-700 rounded-xl px-3 py-2 text-white text-sm focus:outline-none focus:border-indigo-500"
              />
            </div>
            <div className="space-y-1.5">
              <label className="text-xs font-medium text-slate-300">Programme Code</label>
              <input
                type="text"
                value={programmeForm.code}
                onChange={(e) => setProgrammeForm({ ...programmeForm, code: e.target.value })}
                className="w-full bg-slate-900 border border-slate-700 rounded-xl px-3 py-2 text-white text-sm focus:outline-none focus:border-indigo-500"
              />
            </div>
            <div className="space-y-1.5 sm:col-span-2">
              <label className="text-xs font-medium text-slate-300">First Group / Class Name</label>
              <input
                type="text"
                value={programmeForm.groupName}
                onChange={(e) => setProgrammeForm({ ...programmeForm, groupName: e.target.value })}
                className="w-full bg-slate-900 border border-slate-700 rounded-xl px-3 py-2 text-white text-sm focus:outline-none focus:border-indigo-500"
              />
            </div>
            <div className="space-y-1.5">
              <label className="text-xs font-medium text-slate-300">Group Type</label>
              <select
                value={programmeForm.groupType}
                onChange={(e) => setProgrammeForm({ ...programmeForm, groupType: e.target.value as 'ensemble' | 'class' | 'choir' | 'orchestra' | 'band' | 'company' })}
                className="w-full bg-slate-900 border border-slate-700 rounded-xl px-3 py-2 text-white text-sm focus:outline-none focus:border-indigo-500"
              >
                <option value="ensemble">Ensemble</option>
                <option value="class">Class</option>
                <option value="choir">Choir</option>
                <option value="orchestra">Orchestra</option>
                <option value="band">Band</option>
                <option value="company">Dance Company</option>
              </select>
            </div>
          </div>

          <div className="pt-4 flex items-center justify-end">
            <button
              onClick={handleCreateProgrammeAndGroup}
              disabled={actionLoading || !programmeForm.name.trim() || !programmeForm.groupName.trim()}
              className="py-2.5 px-6 bg-indigo-600 hover:bg-indigo-500 text-white rounded-xl font-medium transition flex items-center gap-2"
            >
              Create & Continue
              <ArrowRight className="w-4 h-4" />
            </button>
          </div>
        </div>
      )}

      {/* STEP 10: LEARNER IMPORT */}
      {currentStep === 'learner_import' && (
        <div className="bg-slate-800/60 border border-slate-700/80 rounded-2xl p-8 space-y-6">
          <p className="text-sm text-slate-300">
            Paste CSV data to import learners. You can also skip this and add learners anytime later.
          </p>

          <textarea
            value={csvContent}
            onChange={(e) => setCsvContent(e.target.value)}
            rows={6}
            placeholder={`firstName,lastName,email,phone,dateOfBirth,guardianName,guardianEmail,guardianPhone\nSipho,Nkosi,sipho@example.com,+27820000000,2010-05-12,Thandi Nkosi,thandi@example.com,+27821111111`}
            className="w-full bg-slate-900 border border-slate-700 rounded-xl p-3 text-white text-xs font-mono focus:outline-none focus:border-indigo-500"
          />

          <div className="flex items-center gap-3">
            <button
              type="button"
              onClick={handleValidateCsv}
              disabled={!csvContent.trim()}
              className="py-2 px-4 bg-slate-700 hover:bg-slate-600 text-white rounded-xl text-xs font-medium transition"
            >
              Validate CSV
            </button>
            {csvValidation && (
              <span className={`text-xs ${csvValidation.valid ? 'text-emerald-400' : 'text-amber-400'}`}>
                {csvValidation.valid
                  ? `✓ Valid (${csvValidation.validRows?.length} rows ready)`
                  : `⚠️ ${csvValidation.errors?.[0]?.message || 'Validation error'}`}
              </span>
            )}
          </div>

          <div className="pt-4 flex items-center justify-between">
            <button
              onClick={handleSkip}
              className="text-xs text-slate-400 hover:text-white py-2 px-3 rounded-lg hover:bg-slate-700/50 transition"
            >
              Add learners later (Skip)
            </button>
            <button
              onClick={() => handleNext({ importedCount: csvValidation?.validRows?.length || 0 })}
              disabled={actionLoading}
              className="py-2.5 px-6 bg-indigo-600 hover:bg-indigo-500 text-white rounded-xl font-medium transition flex items-center gap-2"
            >
              Continue
              <ArrowRight className="w-4 h-4" />
            </button>
          </div>
        </div>
      )}

      {/* STEP 11: GUARDIAN SETUP */}
      {currentStep === 'guardian_setup' && (
        <div className="bg-slate-800/60 border border-slate-700/80 rounded-2xl p-8 space-y-6">
          <div className="p-4 rounded-xl bg-slate-900/60 border border-slate-700/60 space-y-2">
            <h3 className="text-sm font-semibold text-white flex items-center gap-2">
              <ShieldCheck className="w-4 h-4 text-indigo-400" />
              Guardian Portal Status
            </h3>
            <p className="text-xs text-slate-400 leading-relaxed">
              Guardians are linked to learners during import or manual registration. Guardian Portal access is currently inactive and will remain so until you choose to send formal portal invitations from Settings.
            </p>
          </div>

          <div className="pt-4 flex items-center justify-between">
            <button
              onClick={handleSkip}
              className="text-xs text-slate-400 hover:text-white py-2 px-3 rounded-lg hover:bg-slate-700/50 transition"
            >
              Skip for now
            </button>
            <button
              onClick={() => handleNext({ guardianSetupStatus: 'ready' })}
              disabled={actionLoading}
              className="py-2.5 px-6 bg-indigo-600 hover:bg-indigo-500 text-white rounded-xl font-medium transition flex items-center gap-2"
            >
              Confirm & Review
              <ArrowRight className="w-4 h-4" />
            </button>
          </div>
        </div>
      )}

      {/* STEP 12 & 13: REVIEW & GO LIVE */}
      {(currentStep === 'review' || currentStep === 'go_live') && (
        <div className="bg-slate-800/60 border border-slate-700/80 rounded-2xl p-8 space-y-6">
          <div className="flex items-center justify-between">
            <h2 className="text-lg font-semibold text-white">Go-Live Readiness Checklist</h2>
            <span className={`text-xs px-3 py-1 rounded-full font-semibold ${
              readiness?.isReady
                ? 'bg-emerald-500/20 text-emerald-400 border border-emerald-500/30'
                : 'bg-amber-500/20 text-amber-400 border border-amber-500/30'
            }`}>
              {readiness?.percentage}% Ready
            </span>
          </div>

          <div className="space-y-3">
            {readiness?.conditions.map((cond) => (
              <div
                key={cond.key}
                className="p-4 rounded-xl bg-slate-900/60 border border-slate-700/60 flex items-start justify-between gap-4"
              >
                <div className="space-y-1">
                  <div className="flex items-center gap-2">
                    <span className="text-sm font-medium text-white">{cond.label}</span>
                    {cond.required && (
                      <span className="text-[10px] text-indigo-300 bg-indigo-500/20 px-1.5 py-0.5 rounded">
                        Required
                      </span>
                    )}
                  </div>
                  <p className="text-xs text-slate-400">{cond.description}</p>
                  {cond.details && (
                    <p className="text-xs text-slate-500">{cond.details}</p>
                  )}
                </div>
                <div className="pt-0.5">
                  {cond.met ? (
                    <CheckCircle2 className="w-5 h-5 text-emerald-400" />
                  ) : (
                    <AlertCircle className="w-5 h-5 text-amber-400" />
                  )}
                </div>
              </div>
            ))}
          </div>

          <div className="pt-4 flex items-center justify-between">
            <button
              onClick={() => setCurrentStep('organisation_profile')}
              className="text-xs text-slate-400 hover:text-white py-2 px-3 rounded-lg hover:bg-slate-700/50 transition flex items-center gap-1.5"
            >
              <ArrowLeft className="w-3.5 h-3.5" />
              Revisit Steps
            </button>
            <button
              onClick={handleGoLive}
              disabled={actionLoading || !readiness?.isReady}
              className={`py-3 px-8 rounded-xl font-semibold transition flex items-center gap-2 ${
                readiness?.isReady
                  ? 'bg-emerald-600 hover:bg-emerald-500 text-white shadow-lg shadow-emerald-600/20'
                  : 'bg-slate-700 text-slate-400 cursor-not-allowed'
              }`}
            >
              <Sparkles className="w-5 h-5" />
              Complete Setup & Go Live
            </button>
          </div>
        </div>
      )}
    </OrganisationOnboardingLayout>
  );
};
