import React, { useState } from 'react';
import { X, Plus, Trash2, Zap, ShieldCheck } from 'lucide-react';
import type { 
  RuleCategory, 
  TriggerType, 
  RulePriority, 
  AutomationActionType, 
  AutomationAction, 
  AutomationRule 
} from '../../../types';
import type { CreateRuleInput } from '../../../services/automation/automationRuleService';

interface RuleBuilderModalProps {
  isOpen: boolean;
  onClose: () => void;
  onSave: (ruleData: CreateRuleInput) => Promise<void>;
  initialRule?: AutomationRule | null;
}

export function RuleBuilderModal({ isOpen, onClose, onSave, initialRule }: RuleBuilderModalProps) {
  const [name, setName] = useState(initialRule?.name || '');
  const [description, setDescription] = useState(initialRule?.description || '');
  const [category, setCategory] = useState<RuleCategory>(initialRule?.ruleCategory || 'attendance');
  const [triggerType, setTriggerType] = useState<TriggerType>(initialRule?.triggerType || 'pattern_detected');
  const [priority, setPriority] = useState<RulePriority>(initialRule?.priority || 'normal');
  const [cooldownMinutes, setCooldownMinutes] = useState(initialRule?.cooldownMinutes || 1440);
  const [deduplicationWindowHours, setDeduplicationWindowHours] = useState(initialRule?.deduplicationWindowHours || 24);
  
  // Trigger config states
  const [consecutiveCount, setConsecutiveCount] = useState(initialRule?.triggerConfig?.consecutiveCount || 3);
  const [thresholdPercent, setThresholdPercent] = useState(initialRule?.triggerConfig?.thresholdPercent || 75);
  const [overdueDays, setOverdueDays] = useState(initialRule?.triggerConfig?.overdueDays || 1);
  const [daysBefore, setDaysBefore] = useState(initialRule?.triggerConfig?.daysBefore || 7);

  // Actions state
  const [actions, setActions] = useState<AutomationAction[]>(
    initialRule?.actions || [
      {
        actionType: 'create_follow_up',
        category: 'attendance',
        priority: 'normal',
        dueDaysFromNow: 3,
        titleTemplate: 'Attention Needed: {{title}}',
        messageTemplate: 'Automated follow-up created by rule.'
      }
    ]
  );

  const [saving, setSaving] = useState(false);
  const [error, setError] = useState<string | null>(null);

  if (!isOpen) return null;

  const handleAddAction = (type: AutomationActionType) => {
    const newAction: AutomationAction = {
      actionType: type,
      priority: 'normal',
      dueDaysFromNow: 3,
      titleTemplate: type === 'create_notification' ? 'Alert: {{title}}' : 'Follow-Up: {{title}}',
      messageTemplate: 'Automated operational item generated by rule.'
    };
    setActions([...actions, newAction]);
  };

  const handleRemoveAction = (index: number) => {
    setActions(actions.filter((_, i) => i !== index));
  };

  const handleActionChange = (index: number, field: keyof AutomationAction, value: string | number | boolean | undefined) => {
    const updated = [...actions];
    updated[index] = { ...updated[index], [field]: value };
    setActions(updated);
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!name.trim()) {
      setError('Please provide a rule name.');
      return;
    }
    if (actions.length === 0) {
      setError('At least one action is required.');
      return;
    }

    try {
      setSaving(true);
      setError(null);

      const triggerConfig: Record<string, unknown> = {};
      if (category === 'attendance') {
        if (triggerType === 'pattern_detected') triggerConfig.consecutiveCount = Number(consecutiveCount);
        if (triggerType === 'threshold_reached') {
          triggerConfig.thresholdPercent = Number(thresholdPercent);
          triggerConfig.minSessions = 4;
        }
      } else if (category === 'finance') {
        triggerConfig.overdueDays = Number(overdueDays);
      } else if (category === 'consent' || category === 'event') {
        triggerConfig.daysBefore = Number(daysBefore);
      }

      await onSave({
        name: name.trim(),
        description: description.trim(),
        ruleCategory: category,
        triggerType,
        triggerConfig,
        conditions: [],
        actions,
        priority,
        cooldownMinutes: Number(cooldownMinutes),
        deduplicationWindowHours: Number(deduplicationWindowHours)
      });
      onClose();
    } catch (err: unknown) {
      setError(err instanceof Error ? err.message : 'Failed to save rule');
    } finally {
      setSaving(false);
    }
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-900/50 backdrop-blur-sm p-4 overflow-y-auto">
      <div className="bg-white rounded-2xl shadow-2xl border border-slate-200 w-full max-w-2xl overflow-hidden my-8 animate-in fade-in zoom-in-95 duration-200">
        {/* Header */}
        <div className="px-6 py-4 bg-slate-50 border-b border-slate-200 flex items-center justify-between">
          <div className="flex items-center gap-2">
            <Zap className="w-5 h-5 text-indigo-600" />
            <h2 className="text-lg font-bold text-slate-900">
              {initialRule ? 'Edit Automation Rule' : 'New Automation Rule'}
            </h2>
          </div>
          <button 
            onClick={onClose} 
            className="p-1 text-slate-400 hover:text-slate-600 rounded-lg hover:bg-slate-100 transition-colors"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        <form onSubmit={handleSubmit} className="p-6 space-y-6 max-h-[80vh] overflow-y-auto">
          {error && (
            <div className="p-3 bg-rose-50 border border-rose-200 rounded-lg text-rose-700 text-sm">
              {error}
            </div>
          )}

          {/* Human Decision Guard Notice */}
          <div className="p-3 bg-amber-50 border border-amber-200 rounded-lg flex items-start gap-2.5 text-xs text-amber-800">
            <ShieldCheck className="w-4 h-4 text-amber-600 shrink-0 mt-0.5" />
            <span>
              <strong>Safe Human Decision Boundary:</strong> Rules can create follow-up tasks, in-app notifications, and draft communications. External communications are never auto-sent without explicit human review.
            </span>
          </div>

          {/* Basic Details */}
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
            <div className="sm:col-span-2">
              <label className="block text-xs font-semibold text-slate-700 uppercase tracking-wider mb-1">
                Rule Name *
              </label>
              <input
                type="text"
                value={name}
                onChange={e => setName(e.target.value)}
                placeholder="e.g. Attendance — 3 Consecutive Absences"
                className="w-full px-3 py-2 border border-slate-300 rounded-lg text-sm focus:ring-2 focus:ring-indigo-500 focus:border-indigo-500 outline-none"
                required
              />
            </div>

            <div className="sm:col-span-2">
              <label className="block text-xs font-semibold text-slate-700 uppercase tracking-wider mb-1">
                Description
              </label>
              <textarea
                value={description}
                onChange={e => setDescription(e.target.value)}
                rows={2}
                placeholder="Operational purpose of this automation rule..."
                className="w-full px-3 py-2 border border-slate-300 rounded-lg text-sm focus:ring-2 focus:ring-indigo-500 focus:border-indigo-500 outline-none"
              />
            </div>

            <div>
              <label className="block text-xs font-semibold text-slate-700 uppercase tracking-wider mb-1">
                Domain Category
              </label>
              <select
                value={category}
                onChange={e => setCategory(e.target.value as RuleCategory)}
                className="w-full px-3 py-2 border border-slate-300 rounded-lg text-sm focus:ring-2 focus:ring-indigo-500 outline-none"
              >
                <option value="attendance">Attendance</option>
                <option value="finance">Finance & Billing</option>
                <option value="consent">Consent & Permissions</option>
                <option value="transport">Transport & Logistics</option>
                <option value="event">Events & Performances</option>
                <option value="instrument">Music Instruments</option>
                <option value="costume">Dance Costumes</option>
                <option value="follow_up">Follow-Up Tasks</option>
                <option value="communication">Communications</option>
                <option value="general">Data Quality / General</option>
              </select>
            </div>

            <div>
              <label className="block text-xs font-semibold text-slate-700 uppercase tracking-wider mb-1">
                Trigger Type
              </label>
              <select
                value={triggerType}
                onChange={e => setTriggerType(e.target.value as TriggerType)}
                className="w-full px-3 py-2 border border-slate-300 rounded-lg text-sm focus:ring-2 focus:ring-indigo-500 outline-none"
              >
                <option value="pattern_detected">Pattern Detected (Streaks, Trends)</option>
                <option value="threshold_reached">Threshold Reached (Percentages, Counts)</option>
                <option value="date_reached">Date Reached (Due Date Passed)</option>
                <option value="date_approaching">Date Approaching (Days Before)</option>
                <option value="status_changed">Status Changed</option>
              </select>
            </div>
          </div>

          {/* Dynamic Trigger Config */}
          <div className="p-4 bg-slate-50 border border-slate-200 rounded-xl space-y-3">
            <h3 className="text-xs font-bold text-slate-700 uppercase tracking-wider">
              Trigger Configuration
            </h3>
            {category === 'attendance' && triggerType === 'pattern_detected' && (
              <div>
                <label className="block text-xs text-slate-600 mb-1">Consecutive Absences Count</label>
                <input
                  type="number"
                  min={1}
                  max={10}
                  value={consecutiveCount}
                  onChange={e => setConsecutiveCount(Number(e.target.value))}
                  className="w-32 px-3 py-1.5 border border-slate-300 rounded-md text-sm"
                />
              </div>
            )}
            {category === 'attendance' && triggerType === 'threshold_reached' && (
              <div>
                <label className="block text-xs text-slate-600 mb-1">Attendance Rate Below (%)</label>
                <input
                  type="number"
                  min={10}
                  max={99}
                  value={thresholdPercent}
                  onChange={e => setThresholdPercent(Number(e.target.value))}
                  className="w-32 px-3 py-1.5 border border-slate-300 rounded-md text-sm"
                />
              </div>
            )}
            {category === 'finance' && (
              <div>
                <label className="block text-xs text-slate-600 mb-1">Days Overdue</label>
                <input
                  type="number"
                  min={1}
                  max={180}
                  value={overdueDays}
                  onChange={e => setOverdueDays(Number(e.target.value))}
                  className="w-32 px-3 py-1.5 border border-slate-300 rounded-md text-sm"
                />
              </div>
            )}
            {(category === 'consent' || category === 'event') && (
              <div>
                <label className="block text-xs text-slate-600 mb-1">Days Before Event</label>
                <input
                  type="number"
                  min={1}
                  max={60}
                  value={daysBefore}
                  onChange={e => setDaysBefore(Number(e.target.value))}
                  className="w-32 px-3 py-1.5 border border-slate-300 rounded-md text-sm"
                />
              </div>
            )}
          </div>

          {/* Safeguards & Cooldown */}
          <div className="grid grid-cols-1 sm:grid-cols-3 gap-4">
            <div>
              <label className="block text-xs font-semibold text-slate-700 uppercase tracking-wider mb-1">
                Priority
              </label>
              <select
                value={priority}
                onChange={e => setPriority(e.target.value as RulePriority)}
                className="w-full px-3 py-2 border border-slate-300 rounded-lg text-sm focus:ring-2 focus:ring-indigo-500 outline-none"
              >
                <option value="low">Low</option>
                <option value="normal">Normal</option>
                <option value="high">High</option>
                <option value="urgent">Urgent</option>
              </select>
            </div>

            <div>
              <label className="block text-xs font-semibold text-slate-700 uppercase tracking-wider mb-1">
                Cooldown (Minutes)
              </label>
              <input
                type="number"
                min={0}
                step={60}
                value={cooldownMinutes}
                onChange={e => setCooldownMinutes(Number(e.target.value))}
                className="w-full px-3 py-2 border border-slate-300 rounded-lg text-sm focus:ring-2 focus:ring-indigo-500 outline-none"
              />
              <span className="text-[10px] text-slate-400">Min time before rule can re-trigger</span>
            </div>

            <div>
              <label className="block text-xs font-semibold text-slate-700 uppercase tracking-wider mb-1">
                Dedup Window (Hours)
              </label>
              <input
                type="number"
                min={1}
                value={deduplicationWindowHours}
                onChange={e => setDeduplicationWindowHours(Number(e.target.value))}
                className="w-full px-3 py-2 border border-slate-300 rounded-lg text-sm focus:ring-2 focus:ring-indigo-500 outline-none"
              />
              <span className="text-[10px] text-slate-400">Ignore repeated triggers for entity</span>
            </div>
          </div>

          {/* Configured Actions */}
          <div className="space-y-3">
            <div className="flex items-center justify-between">
              <h3 className="text-xs font-bold text-slate-700 uppercase tracking-wider">
                Configured Actions ({actions.length})
              </h3>
              <div className="flex items-center gap-2">
                <button
                  type="button"
                  onClick={() => handleAddAction('create_follow_up')}
                  className="px-2.5 py-1 bg-indigo-50 text-indigo-700 hover:bg-indigo-100 rounded text-xs font-medium flex items-center gap-1 transition-colors"
                >
                  <Plus className="w-3 h-3" /> Follow-Up
                </button>
                <button
                  type="button"
                  onClick={() => handleAddAction('create_notification')}
                  className="px-2.5 py-1 bg-sky-50 text-sky-700 hover:bg-sky-100 rounded text-xs font-medium flex items-center gap-1 transition-colors"
                >
                  <Plus className="w-3 h-3" /> Notification
                </button>
                <button
                  type="button"
                  onClick={() => handleAddAction('create_operational_alert')}
                  className="px-2.5 py-1 bg-amber-50 text-amber-700 hover:bg-amber-100 rounded text-xs font-medium flex items-center gap-1 transition-colors"
                >
                  <Plus className="w-3 h-3" /> Alert
                </button>
              </div>
            </div>

            {actions.map((act, index) => (
              <div key={index} className="p-3 bg-white border border-slate-200 rounded-xl space-y-2 relative shadow-sm">
                <div className="flex items-center justify-between">
                  <span className="text-xs font-bold uppercase text-indigo-600">
                    Action {index + 1}: {act.actionType.replace(/_/g, ' ')}
                  </span>
                  <button
                    type="button"
                    onClick={() => handleRemoveAction(index)}
                    className="text-slate-400 hover:text-rose-600 p-1 transition-colors"
                  >
                    <Trash2 className="w-3.5 h-3.5" />
                  </button>
                </div>

                <div className="grid grid-cols-1 sm:grid-cols-2 gap-2 text-xs">
                  <div>
                    <label className="block text-slate-500 mb-0.5">Title Template</label>
                    <input
                      type="text"
                      value={act.titleTemplate || ''}
                      onChange={e => handleActionChange(index, 'titleTemplate', e.target.value)}
                      placeholder="e.g. Overdue: {{title}}"
                      className="w-full px-2.5 py-1.5 border border-slate-300 rounded text-xs"
                    />
                  </div>
                  <div>
                    <label className="block text-slate-500 mb-0.5">Message / Description</label>
                    <input
                      type="text"
                      value={act.messageTemplate || ''}
                      onChange={e => handleActionChange(index, 'messageTemplate', e.target.value)}
                      placeholder="Details of the action..."
                      className="w-full px-2.5 py-1.5 border border-slate-300 rounded text-xs"
                    />
                  </div>
                </div>
              </div>
            ))}
          </div>

          {/* Footer */}
          <div className="pt-4 border-t border-slate-200 flex items-center justify-end gap-3">
            <button
              type="button"
              onClick={onClose}
              className="px-4 py-2 text-sm font-medium text-slate-700 hover:bg-slate-100 rounded-lg transition-colors"
            >
              Cancel
            </button>
            <button
              type="submit"
              disabled={saving}
              className="px-5 py-2 bg-indigo-600 hover:bg-indigo-700 text-white font-medium text-sm rounded-lg shadow-sm transition-colors disabled:opacity-50 flex items-center gap-1.5"
            >
              <Zap className="w-4 h-4" />
              {saving ? 'Saving...' : initialRule ? 'Update Rule' : 'Create Rule'}
            </button>
          </div>
        </form>
      </div>
    </div>
  );
}
